# Generated by Django 4.2.5 on 2023-10-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(db_index=True, max_length=50, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemsName', models.CharField(max_length=50, verbose_name='Имя предмета')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.CharField(max_length=100, verbose_name='Описание предмета')),
                ('itemsCount', models.IntegerField(default=0, verbose_name='Кол-во предметов')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='static/bc_app/images/', verbose_name='Изображение')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bc_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['itemsName'],
            },
        ),
    ]
